Repository shelcia/dynamic-portfolio, pull requests merged in 2024-01, with the labels that each got.

#318 Skills section animated
  src/pages/portfolio/template/template1/styles/style.css
Labels: kwoc23, kwoc

#320 added hamburger menu in template 3
  src/pages/portfolio/template/template3/components/Topbar.jsx
Labels: medium, iwoc24

#322 Added Logo and favicon
  public/favicon.ico
  public/logo.jpg
Labels: medium, iwoc24

#324 Made a change in the Year in copyright Seaction
  src/components/layout/HomeLayout.jsx
Labels: easy, iwoc24

#331 Greeting action added
  .github/workflows/greetings.yml
Labels: easy, iwoc24
